# Uncomment the next line to define a global platform for your project
platform :ios, '8.1'
use_frameworks!
target 'SQKBExample' do
pod 'Alamofire'
pod 'Kingfisher', '~> 3.2.4'
#pod 'MJExtension'
pod 'MJRefresh'
end
